import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";
import AuthProvider from "@/app/auth/Provider";
import React from "react";
import { AxiomWebVitals } from "next-axiom";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AxiomWebVitals />
        <AuthProvider>{children}</AuthProvider>
      </body>
    </html>
  );
}
